### Send POST request with json body
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "username": "username",
  "password": "password"
}

### Send a GET request to a restricted endpoint
## Replace the token with the one you got from the login request
GET http://localhost:8080/api/ping
Authorization: <token>